language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# We need to set all the required env variables before running any test
before_script:
  export WORKSHOPVENUES_ADMIN_NAME="Your Name"
  export WORKSHOPVENUES_ADMIN_EMAIL="youremail@provider.com"
  export WORKSHOPVENUES_DB_ENGINE="django.db.backends.postgresql_psycopg2"
  export WORKSHOPVENUES_DB_NAME="workshopvenues"
  export WORKSHOPVENUES_DB_USER="username"
  export WORKSHOPVENUES_DB_PASSWORD="password"
  export WORKSHOPVENUES_DB_HOST="localhost"
  export WORKSHOPVENUES_DB_PORT=5432
  export WORKSHOPVENUES_STATIC_ROOT=""
  export WORKSHOPVENUES_STATIC_URL="/static/"
  export WORKSHOPVENUES_STATICFILES_ASSETS="static"
  export WORKSHOPVENUES_SECRET_KEY=""
  export WORKSHOPVENUES_DEBUG="True"
  export WORKSHOPVENUES_ALLOWED_HOSTS="*"
  export AWS_ACCESS_KEY_ID=''
  export AWS_SECRET_ACCESS_KEY=''
  export AWS_STORAGE_BUCKET_NAME=''
  export SENDGRID_USERNAME=''
  export SENDGRID_PASSWORD=''
# command to run tests, e.g. python setup.py test
script: workshopvenues/manage.py test --settings=workshopvenues.settings_test venues
